export const INIT_RESTAURANTS = 'INIT_RESTAURANTS'
export const GET_CURRENT_RESTAURANT = 'GET_CURRENT_RESTAURANT'

export const SAGA_INIT_RESTAURANTS = 'SAGA_INIT_RESTAURANTS'
export const SAGA_GET_CURRENT_RESTAURANT = 'SAGA_GET_CURRENT_RESTAURANT'
